# Generated by Django 6.0.3 on 2026-03-17 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='family',
            field=models.ForeignKey(blank=True, help_text='The primary tenant boundary for this user.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.family'),
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('role', models.CharField(choices=[('PARENT', 'Parent'), ('CHILD', 'Child'), ('OTHER', 'Other')], default='CHILD', max_length=10)),
                ('expected_age_at_retirement', models.IntegerField(default=65)),
                ('expected_age_at_death', models.IntegerField(default=99)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='users.family')),
                ('user_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demographic_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
