# Generated by Django 4.2 on 2026-05-20 12:02

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_customuser_family_familymember'),
        ('accounting', '0009_add_statcan_vector_id_to_account'),
        ('assets', '0002_house_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinkingFundProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target_date', models.DateField(help_text='Date by which the full amount must be available.')),
                ('savings_start_date', models.DateField(blank=True, help_text='When contributions began (or are planned to begin). Defaults to today when blank.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinking_fund_projects', to='users.family')),
            ],
            options={
                'ordering': ['target_date'],
            },
        ),
        migrations.CreateModel(
            name='SinkingFundLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('today_price', models.DecimalField(decimal_places=2, help_text="Current estimated cost per unit in today's dollars.", max_digits=15)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10)),
                ('inflation_rate_override', models.DecimalField(blank=True, decimal_places=2, help_text='Manual annual inflation % override. Used when no expense_category is set.', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_category', models.ForeignKey(blank=True, help_text='Expense account whose StatCan CPI vector drives the inflation assumption.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sinking_fund_line_items', to='accounting.account')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='projects.sinkingfundproject')),
                ('source_asset', models.ForeignKey(blank=True, help_text="Existing asset whose accumulated sinking fund is credited against this line item's target.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absorbed_by_line_items', to='assets.tangibleasset')),
            ],
        ),
    ]
