banniere_dict_vd = {'#414 SPORTS EXPERTS ANJOU QC': ['#414 SPORTS EXPERTS ANJOU QC'],
                    '3 AMIGOS - TERREBONNE TERREBONNE QC': ['3 AMIGOS - TERREBONNE TERREBONNE QC'],
                    '3 BRASSEURS ANJOU ANJOU QC': ['3 BRASSEURS ANJOU ANJOU QC'],
                    'AUX 2 TOMATES ORFORD QC': ['AUX 2 TOMATES ORFORD QC'],
                    'BISTRO LE COUP MONTE I REPENTIGNY QC': ['BISTRO LE COUP MONTE I REPENTIGNY QC'],
                    'BISTRO PIC-BOIS CHARLEM CHARLEMAGNE QC': ['BISTRO PIC-BOIS CHARLEM CHARLEMAGNE QC'],
                    'BISTROT INT DORVAL QC': ['BISTROT INT DORVAL QC'],
                    'BOULZEYE PUB MONTREAL QC': ['BOULZEYE PUB MONTREAL QC'],
                    'BULLSEYE SALOON & GRILL MONT-TREMBLANQC': ['BULLSEYE SALOON & GRILL MONT-TREMBLANQC'],
                    'BUVETTE JUNE MONTREAL QC': ['BUVETTE JUNE MONTREAL QC'],
                    'CAFE ISO MONTREAL QC': ['CAFE ISO MONTREAL QC'],
                    'CAFE LES FRAICHES LASSOMPTION QC': ['CAFE LES FRAICHES LASSOMPTION QC'],
                    'CAGE LACHENAIE TERREBONNE QC': ['CAGE LACHENAIE TERREBONNE QC'],
                    'CANAILLES MONTREAL QC': ['CANAILLES MONTREAL QC'],
                    'CAPULUS CAFE MOBILE MONTREAL QC': ['CAPULUS CAFE MOBILE MONTREAL QC'],
                    'CHEZ BAPTISTE MASSON MONTREAL QC': ['CHEZ BAPTISTE MASSON MONTREAL QC'],
                    'DUNNS FAMOUS MONTREAL QC': ['DUNNS FAMOUS MONTREAL QC'],
                    'ELITE PIZZA POINTE-AUX-TRQC': ['ELITE PIZZA POINTE-AUX-TRQC'],
                    'GASTON RESTAURANT APPO MONTREAL QC': ['GASTON RESTAURANT APPO MONTREAL QC'],
                    'HENRI BRASSERIE FRANCA MONTREAL QC': ['HENRI BRASSERIE FRANCA MONTREAL QC'],
                    'L APARTE TERREBONNE QC': ['L APARTE TERREBONNE QC'],
                    "L'HELICOPTERE MONTREAL QC": ["L'HELICOPTERE MONTREAL QC"],
                    "L'OEUFRIER BROMONT BROMONT QC": ["L'OEUFRIER BROMONT BROMONT QC"],
                    'LA BUVETTE RAS L BOCK LA POCATIERE QC': ['LA BUVETTE RAS L BOCK LA POCATIERE QC'],
                    'LA FILLE DU PECHEUR AMQUI QC': ['LA FILLE DU PECHEUR AMQUI QC'],
                    'LA GOULEE TAVERNE GOURM REPENTIGNY QC': ['LA GOULEE TAVERNE GOURM REPENTIGNY QC'],
                    'LA MARCHE A COTE Montreal QC': ['LA MARCHE A COTE Montreal QC'],
                    'LA RIPAILLE REPENTIGNY QC': ['LA RIPAILLE REPENTIGNY QC'],
                    'LA STATION EASTMAN QC': ['LA STATION EASTMAN QC'],
                    'LA SUCCURSALE MONTREAL QC': ['LA SUCCURSALE MONTREAL QC'],
                    'LE BLIND PIG MONTREAL QC': ['LE BLIND PIG MONTREAL QC'],
                    'LE DATE MONTREAL QC': ['LE DATE MONTREAL QC'],
                    'LE DIVINS TANDEM TERREBONNE QC': ['LE DIVINS TANDEM TERREBONNE QC'],
                    'LE LOUNGE SAINT-SAUVEURQC': ['LE LOUNGE SAINT-SAUVEURQC'],
                    'LE NAUFRAGEUR CARLETON QC': ['LE NAUFRAGEUR CARLETON QC'],
                    'LE POKE STATION PAT MONTREAL QC': ['LE POKE STATION PAT MONTREAL QC'],
                    'LES ENFANTS TERRIBLES MONTREAL QC': ['LES ENFANTS TERRIBLES MONTREAL QC'],
                    'LES FRAICHES - EPICERIE DPTE-AUX-TREMBQC': ['LES FRAICHES - EPICERIE DPTE-AUX-TREMBQC'],
                    'LES INSULAIRES MICROBRA LAVAL QC': ['LES INSULAIRES MICROBRA LAVAL QC'],
                    'LES TROIS GARCONS QUEBEC QC': ['LES TROIS GARCONS QUEBEC QC'],
                    'LESPACE PUBLIC BRASSEUR MONTREAL QC': ['LESPACE PUBLIC BRASSEUR MONTREAL QC'],
                    'LOUIS JACOB RESTO BAR LAVAL QC': ['LOUIS JACOB RESTO BAR LAVAL QC'],
                    'LS 9375-8274 Microbras Sainte-FlavieQC': ['LS 9375-8274 Microbras Sainte-FlavieQC'],
                    'MANOIR SAINT SAUVEUR 450-2271811 QC': ['MANOIR SAINT SAUVEUR 450-2271811 QC'],
                    'MARCHE DES ECLUSIERS MONTREAL QC': ['MARCHE DES ECLUSIERS MONTREAL QC'],
                    'MICROBRASSERIE COATICOOK COATICOOK': ['MICROBRASSERIE COATICOOK COATICOOK'],
                    'MICROBRASSERIE LA DIABL MONT-TREMBLANQC': ['MICROBRASSERIE LA DIABL MONT-TREMBLANQC'],
                    'MICROBRASSERIE LA MEMPH MAGOG QC': ['MICROBRASSERIE LA MEMPH MAGOG QC'],
                    'MICROBRASSERIE LE MALB SAINT ANNE DEQC': ['MICROBRASSERIE LE MALB SAINT ANNE DEQC'],
                    'MIKADO QUEBEC QC': ['MIKADO QUEBEC QC'],
                    'PETIT QUEBEC': ['PETIT QUEBEC REPENTIGNY REPENTIGNY QC'],
                    'PIAZZETTA MAGOG MAGOG QC': ['PIAZZETTA MAGOG MAGOG QC'],
                    'PIZZERIA DU BOULEVARD CLERMONT QC': ['PIZZERIA DU BOULEVARD CLERMONT QC'],
                    'PIZZERIA PAT POINTE-AUX-TRQC': ['PIZZERIA PAT POINTE-AUX-TRQC'],
                    'POKE STATION': ['POKE STATION PAT POINTE-AUX-TRBC'],
                    'PUB LORD WILLIAM MONTREAL QC': ['PUB LORD WILLIAM MONTREAL QC'],
                    'PUB ST-PATRICK QUEBEC QC': ['PUB ST-PATRICK QUEBEC QC'],
                    'PULLMAN MONTREAL QC': ['PULLMAN MONTREAL QC'],
                    'RESTAURANT AU PIED DU SAINT-DAMASE QC': ['RESTAURANT AU PIED DU SAINT-DAMASE QC'],
                    'RESTAURANT FAMEUX MONTREAL QC': ['RESTAURANT FAMEUX MONTREAL QC'],
                    'RESTAURANT LA CONFRERIE TERREBONNE QC': ['RESTAURANT LA CONFRERIE TERREBONNE QC'],
                    'RESTAURANT LA FLORIDA LAVAL QC': ['RESTAURANT LA FLORIDA LAVAL QC'],
                    'RESTAURANT WILLIAM GRA MONTREAL QC': ['RESTAURANT WILLIAM GRA MONTREAL QC'],
                    'RESTO INDIAN MONTREAL QC': ['RESTO INDIAN MONTREAL QC'],
                    'RESTO-BAR LE PICK-UP MONTREAL QC': ['RESTO-BAR LE PICK-UP MONTREAL QC'],
                    'SHACK DU MONT-TREMBLANT MONT-TREMBLANQC': ['SHACK DU MONT-TREMBLANT MONT-TREMBLANQC'],
                    'SHAKER LAVAL(TPV) LAVAL QC': ['SHAKER LAVAL(TPV) LAVAL QC'],
                    'SMOKING BBQ MONTREAL QC': ['SMOKING BBQ MONTREAL QC'],
                    'JULES & HENRI MONTREAL QC': ['SP JULES & HENRI MONTREAL QC'],
                    'LA BUVETTE DU QUAI PAMontreal QC': ['SQ *LA BUVETTE DU QUAI PAMontreal QC'],
                    'ST-SAU PUB GOURMAND SAINT-SAUVEURQC': ['ST-SAU PUB GOURMAND SAINT-SAUVEURQC'],
                    'STARBUCKS COFFEE': ['STARBUCKS COFFEE # 599 CHARLEMAGNE QC'],
                    'SUSHI TRI EXPRESS': ['SUSHI TRI EXPRESS MONTREAL QC'],
                    'SUSHISAMA': ['SUSHISAMA POINTE-AUX-TRQC'],
                    'VIEUX MOULIN SAINTE-FLAVIEQC': ['VIEUX MOULIN SAINTE-FLAVIEQC'],
     '2300 SAHARA HOTEL OPERA LAS VEGAS NV': ['2300 SAHARA HOTEL OPERA LAS VEGAS NV'],
     'A&W': ['A&W #5374 DONNACONA QC'],
     'Adonis': ['ADONIS 21943 ANJOU ANJOU QC',
                'ADONIS ANJOU ANJOU QC'
        ],
     'AGENCE DE MOBILITE DURABLMONTREAL QC': ['AGENCE DE MOBILITE DURABLMONTREAL QC'],
     'AIR CAN* 0141116598585AIRCANADA.COMMB': ['AIR CAN* 0141116598585AIRCANADA.COMMB'],
     'AIR CAN* 0141116598586AIRCANADA.COMMB': ['AIR CAN* 0141116598586AIRCANADA.COMMB'],
     'AIRBNB': ['AIRBNB * HM2CTDPRPJ AIRBNB.COM GB',
                'AIRBNB * HM59XRAYFB AIRBNB.COM GB',
                'AIRBNB * HMT2PREXQ8 AIRBNB.COM GB',
                'AIRBNB * HMXPXZYEFX AIRBNB.COM GB',
                                          ],
     'ALLO MON COCO': ['ALLO MON COCO PAT PTE AUX TREMBQC'],
     'AMZ*PremiumpartsWhosal WWW.AMAZON.CAON': ['AMZ*PremiumpartsWhosal WWW.AMAZON.CAON',
                                                'AMZN Mktp CA WWW.AMAZON.CAON',
                                                'AMZN Mktp CA*0L0WZ4IS3 WWW.AMAZON.CAON',
                                                'AMZN Mktp CA*156UA1NW3 WWW.AMAZON.CAON',
                                                'AMZN Mktp CA*1F3HO5IV3 WWW.AMAZON.CAON',
                                                'AMZN Mktp CA*4984K8R43 WWW.AMAZON.CAON',
                                                'AMZN Mktp CA*4L5L22N53 WWW.AMAZON.CAON',
                                                'AMZN Mktp CA*5002Y9IQ3 WWW.AMAZON.CAON',
                                                'AMZN Mktp CA*AS0TR8WS3 WWW.AMAZON.CAON',
                                                'AMZN Mktp CA*CO1SM78J3 WWW.AMAZON.CAON',
                                                'AMZN Mktp CA*CR18X5CT3 WWW.AMAZON.CAON',
                                                'AMZN Mktp CA*EN6CD3NE3 WWW.AMAZON.CAON',
                                                'AMZN Mktp CA*I489R6693 WWW.AMAZON.CAON',
                                                'AMZN Mktp CA*NQ5PS64O3 WWW.AMAZON.CAON',
                                                'AMZN Mktp CA*ON08X2F93 WWW.AMAZON.CAON',
                                                'AMZN Mktp CA*ON15U9843 WWW.AMAZON.CAON',
                                                'AMZN Mktp CA*R02NV4N72 WWW.AMAZON.CAON',
                                                'AMZN Mktp CA*R02XQ7LA2 WWW.AMAZON.CAON',
                                                'AMZN Mktp CA*RB7W18NK2 WWW.AMAZON.CAON',
                                                'AMZN Mktp CA*RT11H5NE0 WWW.AMAZON.CAON',
                                                'AMZN Mktp CA*RU2TG6OY0 WWW.AMAZON.CAON',
                                                'AMZN Mktp CA*RX99W7CZ3 WWW.AMAZON.CAON',
                                                'AMZN Mktp CA*T10UZ0KR0 WWW.AMAZON.CAON',
                                                'AMZN Mktp CA*T16F392L0 WWW.AMAZON.CAON',
                                                'AMZN Mktp CA*T188C8AS2 WWW.AMAZON.CAON',
                                                'AMZN Mktp CA*T35OE2JH2 WWW.AMAZON.CAON',
                                                'AMZN Mktp CA*T66HU1NV3 WWW.AMAZON.CAON',
                                                'AMZN Mktp CA*T98OL3ZE1 WWW.AMAZON.CAON',
                                                'AMZN Mktp CA*TA84J1ZZ1 WWW.AMAZON.CAON',
                                                'AMZN Mktp CA*TK9R88SO2 WWW.AMAZON.CAON',
                                                'AMZN Mktp CA*TQ0828ME2 WWW.AMAZON.CAON',
                                                'AMZN Mktp CA*TQ5FP7010 WWW.AMAZON.CAON',
                                                'AMZN Mktp CA*TQ7D69XB2 WWW.AMAZON.CAON',
                                                'AMZN Mktp CA*TX0II8Z91 WWW.AMAZON.CAON',
                                                'AMZN Mktp CA*TX9DD0OD0 WWW.AMAZON.CAON',
                                                'AMZN Mktp CA*TX9JK69D0 WWW.AMAZON.CAON',
                                                'AMZN Mktp CA*TY0SP8963 WWW.AMAZON.CAON',
                                                'AMZN Mktp CA*VW5AP2J43 WWW.AMAZON.CAON',
                                                'AMZN Mktp CA*XL4LQ88Z3 WWW.AMAZON.CAON',
                                                'AMZN Mktp CA*YM9MP41Y3 WWW.AMAZON.CAON',
                                                'Amazon.ca*KP8828J23 AMAZON.CA ON',
                                                'Amazon.ca*SD6270PY3 AMAZON.CA ON',
                                                'Amazon.ca*W24QU6FL3 AMAZON.CA ON',
                                               ],
     'APPLE': ['APPLE.COM/BILL 866-712-7753 ON',
               'APPLE.COM/BILL TORONTO ON'
              ],
     'APPLIANCE PARTS 866-985-5301 BC': ['APPLIANCE PARTS 866-985-5301 BC'],
     'AU COIN DU PEDALEUR ET REPENTIGNY QC': ['AU COIN DU PEDALEUR ET REPENTIGNY QC'],
     "AUX P'TITS BOCAUX POINTE AUX TRQC": ["AUX P'TITS BOCAUX POINTE AUX TRQC"],
     'AVANT-GARDE MONTREAL QC': ['AVANT-GARDE MONTREAL QC'],
     'BOULANGERIE ARTISANALE LABONAVENTURE QC': ['BOULANGERIE ARTISANALE LABONAVENTURE QC'],
     'BOULANGERIE MARIEPAIN MONMONTREAL QC': ['BOULANGERIE MARIEPAIN MONMONTREAL QC'],
     'BOUTIQUE RAS L BOCK SAINT-JEAN-POQC': ['BOUTIQUE RAS L BOCK SAINT-JEAN-POQC'],
     'BRUNET PLUS ANJOU ANJOU QC': ['BRUNET PLUS ANJOU ANJOU QC'],
     'BRYCE CANYON NATURAL H BRYCE UT': ['BRYCE CANYON NATURAL H BRYCE UT'],
     'Billabong Halifax NS': ['Billabong Halifax NS'],
     'CDNCANCERSOC-DR 888-955-5455 ON': ['CDNCANCERSOC-DR 888-955-5455 ON'],
     'CHOCOLATS FAVORIS REPEN REPENTIGNY QC': ['CHOCOLATS FAVORIS REPEN REPENTIGNY QC'],
     'CINEMA MAGOG MAGOG QC': ['CINEMA MAGOG MAGOG QC'],
     'CINEMA TRIOMPHE INC. TERREBONNE QC': ['CINEMA TRIOMPHE INC. TERREBONNE QC'],
     'CINEMAS CINE ENT. 450-581-5757 QC': ['CINEMAS CINE ENT. 450-581-5757 QC'],
     'CITY OF KINGSTON-PARKING KINGSTON ON': ['CITY OF KINGSTON-PARKING KINGSTON ON'],
     'COBIEBOUTIQUE LONDON GB': ['COBIEBOUTIQUE LONDON GB'],
     'CONCORDIA - RECREATION MONTREAL QC': ['CONCORDIA - RECREATION MONTREAL QC'],
     'COUCHE-TARD': ['COUCHE-TARD # 1219 CHARLEMAGNE QC'],
     'CPC / SCP 227730 MONTRÉAL QC': ['CPC / SCP 227730 MONTRÉAL QC'],
     'CREMERIE LEGARDEUR REPENTIGNY QC': ['CREMERIE LEGARDEUR REPENTIGNY QC'],
     'CROISIERES NAVARK LONGUEUIL QC': ['CROISIERES NAVARK LONGUEUIL QC'],
     'CROIX BLEUE/BLUE CROSS 888-888-8888 QC': ['CROIX BLEUE/BLUE CROSS 888-888-8888 QC'],
     'DEFI DANIEL LEQUIN JOLIETTE QC': ['DEFI DANIEL LEQUIN JOLIETTE QC'],
     'DELICES LACTES POINTE AUX TRQC': ['DELICES LACTES POINTE AUX TRQC'],
     'DOLLARAMA': ['DOLLARAMA # 285 REPENTIGNY QC',
                   'DOLLARAMA #1362 POINTE-AUX-TRQC',
                  ],
     'DON PRIMADANSE MONTREAL QC': ['DON PRIMADANSE MONTREAL QC'],
     'DVERT MAGOG': ['DVERT MAGOG'],
     'Decathlon': ['Decathlon Canada Inc. Montreal QC'],
     'ERABLIERE AU RYTHME DES TSAINT-LIN-LAUQC': ['ERABLIERE AU RYTHME DES TSAINT-LIN-LAUQC'],
     'ESSO COUCH': ['ESSO COUCHE-TARD SAINT-LAMBERTQC'],
     'ETSY ETSY.COM IE': ['ETSY ETSY.COM IE'],
     'EXPEDIA 72495655094635 EXPEDIA.CA ON': ['EXPEDIA 72495655094635 EXPEDIA.CA ON'],
     'FLASHFOOD': ['FLASHFOOD TORONTO ON'],
     'FLO SERVICES QUEBEC QC': ['FLO SERVICES QUEBEC QC'],
     'FONDATION CHRISTIAN VA MAGOG QC': ['FONDATION CHRISTIAN VA MAGOG QC'],
     'FOODHERO': ['FOODHERO MONTREAL',
                  'FOODHERO MONTREAL QC',
                 ],
     'FROMAGERIE DU LITTORAL BAIE-DES-SABLQC': ['FROMAGERIE DU LITTORAL BAIE-DES-SABLQC'],
     'GEOPARC DE PERCE PERCE QC': ['GEOPARC DE PERCE PERCE QC'],
     'GLOBAL EXC 8 CASA NOUACEUR MA': ['GLOBAL EXC 8 CASA NOUACEUR MA'],
     'GLOBO #4534 MONTREAL QC': ['GLOBO #4534 MONTREAL QC',
                                 'GLOBO CANADA- E-COMMER SAINT- LAURENQC',
                                 'GLOBOSHOES.COM MONTREAL QC',
                                ],
     'H&M CA #087- GALERIES REPENTIGNY QC': ['H&M CA #087- GALERIES REPENTIGNY QC'],
     'HEBERGEMENT MT TREMBLA 10MT TREMBLANT QC': ['HEBERGEMENT MT TREMBLA 10MT TREMBLANT QC'],
     'HORIZON ROC MONTREAL QC': ['HORIZON ROC MONTREAL QC'],
     'HOTEL SUITE LAC BROME FOSTER QC': ['HOTEL SUITE LAC BROME FOSTER QC'],
     'IGA': ['IGA #8168 MONTREAL QC',
             'IGA EXTRA # 8528 TERREBONNE QC',
             'IGA EXTRA 259 ST-LEONARD QC',
            ],
     'INSCRIPTIONENLIGNE.CA SAINT-EUSTACHQC': ['INSCRIPTIONENLIGNE.CA SAINT-EUSTACHQC'],
     'JEAN COUTU': ['JEAN COUTU 045 POINTE AUX TRQC',
                    'JEAN COUTU 046 REPENTIGNY QC',
                    'JEAN COUTU 341 REPENTIGNY QC',
                   ],
     'KIM PHAT': ['KIM PHAT #3733 MONTREAL QC'],
     'KLINIK DENTAIRE LABERGE NREPENTIGNY QC': ['KLINIK DENTAIRE LABERGE NREPENTIGNY QC'],
     'KNIX WEAR INC TORONTO ON': ['KNIX WEAR INC TORONTO ON'],
     'SIMONS': ['LA MAISON SIMONS INC (ANJANJOU QC',
                'LA MAISON SIMONS INC(QUE)QUEBEC QC',
                'SIMONS WEB QUEBEC QC',
               ],
     "LA MIE D'ORFORD ORFORD QC": ["LA MIE D'ORFORD ORFORD QC"],
     'LA VIE EN ROSE': ['LA VIE EN ROSE INC MONTREAL QC'],
     'LAITERIE COATICOOK COATICOOK QC': ['LAITERIE COATICOOK COATICOOK QC'],
     'LCBO': ['LCBO/RAO #0071 GANANOQUE ON',
              'LCBO/RAO #0449 WELLINGTON ON'
             ],
     'LE CIRCUIT ELECTRIQUE MONTREAL QC': ['LE CIRCUIT ELECTRIQUE MONTREAL QC'],
     'LE PAPETIER LE LIBRAIRE REPENTIGNY QC': ['LE PAPETIER LE LIBRAIRE REPENTIGNY QC'],
     'LEPOINTDEVENTE.COM QUEBEC CITY QC': ['LEPOINTDEVENTE.COM QUEBEC CITY QC'],
     'LES ANIMALERIES T.D. ZOO POINTE-AUX-TRQC': ['LES ANIMALERIES T.D. ZOO POINTE-AUX-TRQC'],
     'LIBRAIRIE RENAUD BRAY MONTREAL QC': ['LIBRAIRIE RENAUD BRAY MONTREAL QC',
                                           'LIBRAIRIE RENAUD BRAY REPENTIGNY QC',
                                          ],
     'LINEN CHEST 801 WEB ONLINLAVAL QC': ['LINEN CHEST 801 WEB ONLINLAVAL QC'],
     'LS 9394-5459 Quebec I Montreal QC': ['LS 9394-5459 Quebec I Montreal QC'],
     'LUNETTERIE CORBEIL SAINT-LEONARDQC': ['LUNETTERIE CORBEIL SAINT-LEONARDQC'],
     "LUSH GALERIES D'ANJOU VILLE D'ANJOUQC": ["LUSH GALERIES D'ANJOU VILLE D'ANJOUQC"],
     'MAGASIN CDN': ['MAGASIN CDN TIRE #00009 ST LEONARD QC',
                                               'MAGASIN CDN TIRE #0303 MONTREAL QC'
                                              ],
     'MARCHE NOTRE DAME 2225 MONTREAL QC': ['MARCHE NOTRE DAME 2225 MONTREAL QC'],
     'MARCHE RICHELIEU QUEBEC QC': ['MARCHE RICHELIEU QUEBEC QC'],
     'MARCHE ST JEAN BAPTI 2 POINTE AUX TRQC': ['MARCHE ST JEAN BAPTI 2 POINTE AUX TRQC'],
     'MAXI': ['MAXI #8622 LACHENAIE QC',
              'MAXI #8622 TERREBONNE QC',
              'MAXI #8987 * POINTE-AUX-TRQC',
              'MAXI #8987 POINTE-AUX-TRQC',
              'MAXI & CIE REPENTIGNY REPENTIGNY QC',
             ],
     "MCDONALD": ["MCDONALD'S #10630 Q04 BERTHIERVILLEQC"
                  ,"MCDONALD'S #11258 DONNACONA QC"
                  ,"MCDONALD'S #11760 SAINT-JEROME QC"
                  ,"MCDONALD'S #12013 Q04 MONTREAL QC"
                  ,"MCDONALD'S #16553 SAINTE-JULIE QC"
                  ,"MCDONALD'S #18127 QPS ANGE-GARDIEN QC"
                  ,"MCDONALD'S #22029 SAINT-SAUVEURQC"
                  ,"MCDONALD'S #26046 Q04 ST LEONARD QC"
                  ,"MCDONALD'S #2635 Q04 MONTREAL QC"
                  ,"MCDONALD'S #40296 MONTREAL QC"
                 ],
     'METRO': ['METRO 159 GANANOQUE ON'
               ,'METRO BEAUBIEN MONTREAL QC'
               ,'METRO BOUCHER JEAN MAT SAINT JEAN DEQC'
               ,'METRO DE LA ROUSSELIER POINTE AUX TRQC'
               ,'METRO EN LIGNE 2445 SAINTE ROSE QC'
               ,'METRO FOGARTY CHARLEMAGNE QC'
               ,'METRO MARQUIS REPENTIG REPENTIGNY QC'
               ,'METRO PLOUFFE MAGOG MAGOG'
               ,'METRO PLOUFFE MAGOG MAGOG QC'
              ],
     'MEUBLES RD': ['MEUBLES RD/12424 VICTORIAVILLEQC'],
     'MISSKIT PHOTO INC. SAINT-CHARLESQC': ['MISSKIT PHOTO INC. SAINT-CHARLESQC'],
     'NATH & COMPAGNIE PERCE QC': ['NATH & COMPAGNIE PERCE QC'],
     'CENTRECOMROUSSIN': ['NBX*CENTRECOMROUSSIN 514-6454519 QC'
                          ,'NBX*CENTRECOMROUSSIN POINTE-AUX-TRQC'
                          ,'NBX*CENTREEDOUARDRIVET 514-9052105 QC',
                         ],
     'NETFLIX': ['NETFLIX.COM 844-5052993 BC',
                 'NETFLIX.COM 866-716-0414 ON',
                 'NETFLIX.COM Vancover BC',
                ],
     'Nespresso': ['Nespresso Canada Toronto ON'],
     'OLDNAVY': ['OLDNAVY.COM 2944 505-462-0076 ON'],
     'OREGON LAVAL QC': ['OREGON LAVAL QC'],
     'PASTA AND FUMO MAGOG QC': ['PASTA AND FUMO MAGOG QC'],
     'PATRICK MORIN': ['PATRICK MORIN 11 POINTE-AUX-TRQC'],
     'PAYPAL *FORMEDUC 4188427523 QC': ['PAYPAL *FORMEDUC 4188427523 QC'],
     'PERFECTION.CA LONGUEUIL QC': ['PERFECTION.CA LONGUEUIL QC'],
     'PETITE MARCHE': ['PETITE MARCHE MONTREAL QC'],
     'PETRO CANADA': ['PETRO CANADA 16137 GASPE QC',
                      'PETRO CANADA10492 SAINTE LUCE QC',
                      'PETRO CANADA13094 ANGE GRDN DE QC',
                      'PETRO CANADA14110 MONTREAL QC',
                      'PETRO CANADA16114 ST SIMON QC',
                     ],
     'PHARMACIE VINH THE JIMMY MONTREAL QC': ['PHARMACIE VINH THE JIMMY MONTREAL QC'],
     'PHARMAPRIX': ['PHARMAPRIX #0061 MONTREAL QC',
                    'PHARMAPRIX #0061 PTE AUX TREMBQC'
                   ],
     'PROVIGO': ['PROVIGO LE GARDEUR #85 LE GARDEUR QC'],
     'PROXIM': ['PROXI EXTRA ORFORD ORFORD QC'],
     'PUBLICITEJL 5147554377 QC': ['PUBLICITEJL 5147554377 QC'],
     'Prezi, Inc. 415-4948313 CA': ['Prezi, Inc. 415-4948313 CA'],
     'QUEBECLOISIRS PLACE VE MONTREAL QC': ['QUEBECLOISIRS PLACE VE MONTREAL QC'],
     'RACEROSTER PRISON LONDON ON': ['RACEROSTER PRISON LONDON ON'],
     'RAM 1479652367222MONTREAL QC': ['RAM 1479652367222MONTREAL QC'],
     'RAM 1479652367225MONTREAL QC': ['RAM 1479652367225MONTREAL QC'],
     'RAM 1479652367226MONTREAL QC': ['RAM 1479652367226MONTREAL QC'],
     'REITMANS': ['REITMANS #1499 MONTREAL',
                  'REITMANS #443 REPENTIGNY QC',
                  'REITMANS 1499 Montreal QC',
                 ],
     'MITSUBISHI': ['REPENTIGNY MITSUBISHI REPENTIGNY QC'],
     'RIVIERE EMERAUDE PERCE QC': ['RIVIERE EMERAUDE PERCE QC'],
     'ROCKY MOUNTAIN CHOCOLATE MONT-TREMBLANQC': ['ROCKY MOUNTAIN CHOCOLATE MONT-TREMBLANQC'],
     "RUBY'S GENERAL STORE BRYCE UT": ["RUBY'S GENERAL STORE BRYCE UT"],
     'RW & CO.': ['RW #2499 MONTREAL QC',
                  'RW & CO. #2216 ANJOU QC',
                  'RWCO 2499 Montreal QC',
                 ],
     'SAQ': ['SAQ.COM/12424 QUEBEC QC',
             'SAQ23004 BROSSARD QC',
             "SAQ23011 HALLES D'ANJOU MONTREAL QC",
             'SAQ23064 SHERBROOKE ES MONTREAL QC',
             'SAQ23070 REPENTIGNY REPENTIGNY QC',
             'SAQ23082 MAGOG MAGOG',
             'SAQ23082 MAGOG MAGOG QC',
             'SAQ23091 ST-DONAT MONTREAL QC',
             'SAQ23095 BROMONT BROMONT QC',
             'SAQ23106 DE LA POINTE POINTE-AUX-TRQC',
             'SAQ23106CARREFOUR DE LA MONTREAL QC',
             'SAQ23199 SAQ.COM MONTREAL QC',
             'SAQ23303 TERREBONNE-MTEE TERREBONNE QC',
             'SAQ23327 REPENTIGNY REPENTIGNY QC',
             'SAQ33532 CLERMONT CLERMONT QC',
            ],
     'CLOSSON CHASE VINEYARD HILLIER ON': ['CLOSSON CHASE VINEYARD HILLIER ON'],
     'COUNTY CIDER PICTON ON': ['COUNTY CIDER PICTON ON'],
     'Canton Brasse Orford QC': ['Canton Brasse Orford QC'],
     'DOMAINE DARIUS HILLIER ON': ['DOMAINE DARIUS HILLIER ON'],
     'KARLO ESTATES WELLINGTON ON': ['KARLO ESTATES WELLINGTON ON'],
     'NORMAN HARDIE WINERY AND WELLINGTON ON': ['NORMAN HARDIE WINERY AND WELLINGTON ON'],
     'O DWYER DISTILLERIE GASPE QC': ['O DWYER DISTILLERIE GASPE QC'],
     'REDTAIL VINEYARD CONSECON ON': ['REDTAIL VINEYARD CONSECON ON'],
     'ROSEHALL RUN VINEYARDS WELLINGTON ON': ['ROSEHALL RUN VINEYARDS WELLINGTON ON'],
     'SLAKE BREWING PICTON ON': ['SLAKE BREWING PICTON ON'],
     'HINTERLAND WINE COMPAPrince EdwardON': ['SQ *HINTERLAND WINE COMPAPrince EdwardON'],
     'PARSONS BREWING COMPAPrince EdwardON': ['SQ *PARSONS BREWING COMPAPrince EdwardON'],
     'SEPAQ': ['SEPAQ 1 800 665 6527 QUEBEC',
               'SEPAQ 1 800 665 6527 QUEBEC QC',
               'SEPAQ YAMASKA ROXTON POND QC',
              ],
     'SERVICE CANADA': ['SERVICE CANADA PT AUX TR PT AUX TREMB QC'],
     'SHEIN.COM Toronto ON': ['SHEIN.COM Toronto ON'],
     'SHELL': ['SHELL C81389 CHARLEMAGNE QC',
               'SHELL OIL10007497018 CEDAR CITY UT',
              ],
     'SOCIETE DES TRAVERSIER SOREL-TRACY QC': ['SOCIETE DES TRAVERSIER SOREL-TRACY QC'],
     'SOS LABYRINTHE': ['SOS LABYRINTHE MONTREAL QC'],
     'BKIND PRODUCTS MONTREAL QC': ['SP BKIND PRODUCTS MONTREAL QC'],
     'CANADA VALISE DEP ST-LAURENT QC': ['SP CANADA VALISE DEP ST-LAURENT QC'],
     'JOELLE COLLECTION TROIS-RIVIEREQC': ['SP JOELLE COLLECTION TROIS-RIVIEREQC'],
     'MESBOBETTES.CA': ['SP MESBOBETTES.CA SHERBROOKE QC'],
     'MONSIEUR COCKTAIL': ['SP MONSIEUR COCKTAIL QUEBEC CITY QC'],
     'SP MONTELLE INTIMATE MONTREAL QC': ['SP MONTELLE INTIMATE MONTREAL QC'],
     'YELLOW SHOES': ['SP YELLOW SHOES ECOM MONTREAL QC'],
     'YUL RUN CANADA MONTREAL QC': ['SP YUL RUN CANADA MONTREAL QC'],
     'SHOWTIME INC. Mont-TremblanQC': ['SQ *5678 SHOWTIME INC. Mont-TremblanQC'],
     '*9483-1104 QUEBEC INC.LANORAIE QC': ['SQ *9483-1104 QUEBEC INC.LANORAIE QC'],
     '*FERME LA VRAIE VIE Saint-Zenon QC': ['SQ *FERME LA VRAIE VIE Saint-Zenon QC'],
     'FORUM Terrebonne QC': ['SQ *FORUM Terrebonne QC'],
     "L'ATELIER DE CAFE Foster QC": ["SQ *L'ATELIER DE CAFE Foster QC"],
     'MIEL MORAND INC. Saint-Zenon QC': ['SQ *MIEL MORAND INC. Saint-Zenon QC'],
     'STOCK AND ROW Bloomfield ON': ['SQ *STOCK AND ROW Bloomfield ON'],
     'STM': ['STM HONORE BEAUG DIN101 MONTREAL QC',
             'STM LAURIER DIN101 MONTREAL QC',
             'STM LOGE LANGELIER N101 MONTREAL QC',
            ],
     'SUPER C': ['SUPER C B ST PAUL 261 BAIE SAINT PAQC',
                 'SUPER C PAT 5963 POINTE AUX TRQC',
                 'SUPER C REPENTIGNY REPENTIGNY QC',
                 'SUPER C ST LEONARD SAINT LEONARDQC',
                ],
     'SUZY SHIER': ['SUZY SHIER #7846 TERREBONNE QC'],
     'Ski Bromont': ['Ski Bromont Online BROMONT QC'],
     'TEMU': ['TEMU.COM VICTORIA BC',
              'TEMU.COM WWW.TEMU.COM BC'
             ],
     "THE CHILDREN'S PLACE": ["THE CHILDREN'S PLACE #300ANJOU QC"],
     'TIM HORTONS': ['TIM HORTONS #1151 MONTREAL QC',
                     'TIM HORTONS #2671 ANJOU QC'
                    ],
     'TOMATE BASILIC': ['TOMATE BASILIC PAT POINTE-AUX-TRQC',
                                            'TOMATE BASILIC POINTE-AUX-TRQC'
                                           ],
     'TOWN OF SPRINGDALE SPRINGDALE UT': ['TOWN OF SPRINGDALE SPRINGDALE UT'],
     'TRAVERSE RDL ST-SIMEON RIVIERE-DU-LOQC': ['TRAVERSE RDL ST-SIMEON RIVIERE-DU-LOQC'],
     'TUANGO': ['TUANGO INC/#LD-0063868 MONTREAL QC',
                'TUANGO INC/#LD-0068960 MONTREAL QC',
                'TUANGO INC/#LD-0079190 MONTREAL QC',
               ],
     'ULTRAMAR': ['ULTRAMAR 24405 POINTE-AUX-TRQC'],
     'UNARBREPOURMONQUARTIER MONTREAL QC': ['UNARBREPOURMONQUARTIER MONTREAL QC'],
     'WAL-MART': ['WAL-MART STORE#1169 POINTE-AUX-TRQC',
                  'WALMART.CA MISSISSAUGA ON'
                 ],
     'WINNERS': ['WINNERS 474 MONTREAL QC'],
     'WOLVERINE WORLDWIDE': ['WOLVERINE WORLDWIDE CANADMISSISSAUGA ON'],
     'Y** LE GROUPE ARCANTIA MONTREAL QC': ['Y** LE GROUPE ARCANTIA MONTREAL QC'],
     'YUL CAMDEN DORVAL QC': ['YUL CAMDEN DORVAL QC'],
     'ZION NATIONAL PARK SPRINGDALE UT': ['ZION NATIONAL PARK SPRINGDALE UT'],
     'aliexpress': ['aliexpress Vancouver BC'],
    }
banniere_dict_ws = {
    "SUPER C": ["Super C Pte Aux Trembl",
                                'Super C La Plaine 2598',
                                'Super C Repentigny',
                                ],
    "COSTCO": ["Costco Wholesale W525", ],
    "METRO": ['Metro De La Rousselier',
              'Supermarche J P V Plou',
              'Marche Plouffe Bromont',
              'Metro Fogarty',
              ],
    "ADONIS": ['Adonis Anjou',
               ],
    'MAXI': ['Maxi',
             'Maxi & Cie Repentigny',
             ],
    'IGA': ['Iga',
            ],
    'Foodhero': ['Foodhero', 'FOODHERO MONTREAL QC', ],
    'KIM PHAT': ['Kim Phat', ],
    'Les Fraiches - Epiceri': ['Les Fraiches - Epiceri'],
    'Ferme Sarrazin': ['Ferme Sarrazin'],
    'Marche Toit Rouge': ['Marche Toit Rouge'],
    'Tradition': ['Tradition'],
    'Charcuterie De Tours (': ['Charcuterie De Tours ('],
    'Marche Afrique St-Deni': ['Marche Afrique St-Deni', ],
    'Nespresso Canada': ['Nespresso Canada', ],
    'Walmart': ['Walmart',
                ],
    "SAQ": ['Saq23106carrefour De L',
            'Saq23082 Magog Rue Pri',
            'Saq23327 Repentigny -',
            'Saq23303 Terrebonne-Mt',
            'Saq23380 St-Sauveur-De',
            'Saq23001 Ste-Catherine',
            'Saq23070 Repentigny Bo',
            'Saq33551 Ste-Anne-Des-',
            'La Vignoble Le Cep Dar',
            'Saq33554 Carleton',

            ],
    'Mitsubishi': ['Repentigny Mitsubishi'],
    "STM": ['Stm Loge St Laurent N1',
            'Stm Laurier Din101',
            'Stm Loge Lionel Groulx',
            'Stm Loge Radisson N101',
            'Stm Loge Charlevoix N1',
            'Stm Loge Honor Beaugra',
            'Stm Loge St Laurent N1',
            'Stm Studio Photo',
            'Stm Loge Berri Uqam N1',
            'Stm Berri Uqam Din102/',
            'Stm Saint Lauren Din10',

            ],
    'Interest earned': ['Interest earned'],
    'Cashback received': ['Cashback received', 'Cashback - Cash Card', ],
    'Deposit': ['Deposit'],
    'Patrick Morin': ['Patrick Morin 11'],
    'Winners': ['Winners 474'],
    'Dollarama': ['Dollarama', ],
    'Tim Hortons': ['Tim Hortons', ],
    "Mcdonald's": ["Mcdonald's", ],
    "L' Echoppe Des Fromage": ["L' Echoppe Des Fromage", ],
    'Restaurant Le Boucan': ['Restaurant Le Boucan', ],
    'Spanel Crepes Et Gourm': ['Spanel Crepes Et Gourm'],
    'Kumamoto Ramen': ['Kumamoto Ramen'],
    'Grumpys Bar': ['Grumpys Bar'],
    'Lsp*Canton Brasse': ['Lsp*Canton Brasse'],
    'Pharmaprix': ['PHARMAPRIX #0061 PTE AUX TREMB QC', 'Pharmaprix'],
    'Jean Coutu': ['Jean Coutu 045', 'Jean Coutu 267', ],
    'Sushi Shama': ['Sushi Sama (pat)', ],
    'Chartwells (cafétéria DJ)': ['Chartwells 41476', ],
    'Amazon': ['Amzn Mktp Ca', 'Amazon', ],
    'Yellow': ['Yellow'],
    'Boutique Ricardo': ['Ls Boutique Ricardo', ],
}
categorie_comptable = {
    'Food purchased from stores': ["Super C",
                                                     "Costco",
                                                     "Metro",
                                                     "Adonis",
                                                     'Maxi',
                                                     'IGA',
                                                     'Kim Phat',
                                                     'FLASHFOOD',
                                                     'FOODHERO',
                                                     'FROMAGERIE DU LITTORAL BAIE-DES-SABLQC',
                                                     'IGA',
                                                     'KIM PHAT',
                                                     'MARCHE NOTRE DAME 2225 MONTREAL QC',
                                                     'MARCHE RICHELIEU QUEBEC QC',
                                                     'MARCHE ST JEAN BAPTI 2 POINTE AUX TRQC',
                                                     'MAXI',
                                                     'METRO',
                                                     'PROVIGO',
                                                     'SUPER C',
                                                     'COSTCO',
                                                     'SUPER C',
                                                     'Ferme Sarrazin',
                                                     'Marche Toit Rouge',
                                                     'Tradition',
                                                     'Charcuterie De Tours (',

                                                     ],
    'Alcoholic beverages': ["SAQ",
                          'LCBO',
                          'CLOSSON CHASE VINEYARD HILLIER ON',
                          'COUNTY CIDER PICTON ON',
                          'Canton Brasse Orford QC',
                          'DOMAINE DARIUS HILLIER ON',
                          'KARLO ESTATES WELLINGTON ON',
                          'NORMAN HARDIE WINERY AND WELLINGTON ON',
                          'O DWYER DISTILLERIE GASPE QC',
                          'REDTAIL VINEYARD CONSECON ON',
                          'ROSEHALL RUN VINEYARDS WELLINGTON ON',
                          'SLAKE BREWING PICTON ON',
                          'SQ *HINTERLAND WINE COMPAPrince EdwardON',
                          'SQ *PARSONS BREWING COMPAPrince EdwardON',
                          ],
    'Food purchased from restaurants': ['3 AMIGOS - TERREBONNE TERREBONNE QC',
                                      '3 BRASSEURS ANJOU ANJOU QC',
                                      'AUX 2 TOMATES ORFORD QC',
                                      'ALLO MON COCO',
                                      'BISTRO LE COUP MONTE I REPENTIGNY QC',
                                      'BISTRO PIC-BOIS CHARLEM CHARLEMAGNE QC',
                                      'BISTROT INT DORVAL QC',
                                      'BOULZEYE PUB MONTREAL QC',
                                      'BULLSEYE SALOON & GRILL MONT-TREMBLANQC',
                                      'BUVETTE JUNE MONTREAL QC',
                                      'CAFE ISO MONTREAL QC',
                                      'CAFE LES FRAICHES LASSOMPTION QC',
                                      'CAGE LACHENAIE TERREBONNE QC',
                                      'CANAILLES MONTREAL QC',
                                      'CAPULUS CAFE MOBILE MONTREAL QC',
                                      'CHEZ BAPTISTE MASSON MONTREAL QC',
                                      'DUNNS FAMOUS MONTREAL QC',
                                      'ELITE PIZZA POINTE-AUX-TRQC',
                                      'GASTON RESTAURANT APPO MONTREAL QC',
                                      'HENRI BRASSERIE FRANCA MONTREAL QC',
                                      'L APARTE TERREBONNE QC',
                                      "L'HELICOPTERE MONTREAL QC",
                                      "L'OEUFRIER BROMONT BROMONT QC",
                                      'LA BUVETTE RAS L BOCK LA POCATIERE QC',
                                      'LA FILLE DU PECHEUR AMQUI QC',
                                      'LA GOULEE TAVERNE GOURM REPENTIGNY QC',
                                      'LA MARCHE A COTE Montreal QC',
                                      'LA RIPAILLE REPENTIGNY QC',
                                      'LA STATION EASTMAN QC',
                                      'LA SUCCURSALE MONTREAL QC',
                                      'LE BLIND PIG MONTREAL QC',
                                      'LE DATE MONTREAL QC',
                                      'LE DIVINS TANDEM TERREBONNE QC',
                                      'LE LOUNGE SAINT-SAUVEURQC',
                                      'LE NAUFRAGEUR CARLETON QC',
                                      'LE POKE STATION PAT MONTREAL QC',
                                      'LES ENFANTS TERRIBLES MONTREAL QC',
                                      'LES FRAICHES - EPICERIE DPTE-AUX-TREMBQC',
                                      'LES INSULAIRES MICROBRA LAVAL QC',
                                      'LES TROIS GARCONS QUEBEC QC',
                                      'LESPACE PUBLIC BRASSEUR MONTREAL QC',
                                      'LOUIS JACOB RESTO BAR LAVAL QC',
                                      'LS 9375-8274 Microbras Sainte-FlavieQC',
                                      'MANOIR SAINT SAUVEUR 450-2271811 QC',
                                      'MARCHE DES ECLUSIERS MONTREAL QC',
                                      'MICROBRASSERIE COATICOOK COATICOOK',
                                      'MICROBRASSERIE LA DIABL MONT-TREMBLANQC',
                                      'MICROBRASSERIE LA MEMPH MAGOG QC',
                                      'MICROBRASSERIE LE MALB SAINT ANNE DEQC',
                                      'MIKADO QUEBEC QC',
                                      'PETIT QUEBEC REPENTIGNY REPENTIGNY QC',
                                      'PIAZZETTA MAGOG MAGOG QC',
                                      'PIZZERIA DU BOULEVARD CLERMONT QC',
                                      'PIZZERIA PAT POINTE-AUX-TRQC',
                                      'POKE STATION PAT POINTE-AUX-TRBC',
                                      'PUB LORD WILLIAM MONTREAL QC',
                                      'PUB ST-PATRICK QUEBEC QC',
                                      'PULLMAN MONTREAL QC',
                                      'RESTAURANT AU PIED DU SAINT-DAMASE QC',
                                      'RESTAURANT FAMEUX MONTREAL QC',
                                      'RESTAURANT LA CONFRERIE TERREBONNE QC',
                                      'RESTAURANT LA FLORIDA LAVAL QC',
                                      'RESTAURANT WILLIAM GRA MONTREAL QC',
                                      'RESTO INDIAN MONTREAL QC',
                                      'RESTO-BAR LE PICK-UP MONTREAL QC',
                                      'SHACK DU MONT-TREMBLANT MONT-TREMBLANQC',
                                      'SHAKER LAVAL(TPV) LAVAL QC',
                                      'SMOKING BBQ MONTREAL QC',
                                      'SP JULES & HENRI MONTREAL QC',
                                      'SQ *LA BUVETTE DU QUAI PAMontreal QC',
                                      'ST-SAU PUB GOURMAND SAINT-SAUVEURQC',
                                      'STARBUCKS COFFEE # 599 CHARLEMAGNE QC',
                                      'SUSHI TRI EXPRESS MONTREAL QC',
                                      'SUSHISAMA POINTE-AUX-TRQC',
                                      'VIEUX MOULIN SAINTE-FLAVIEQC',
                                      'AU COIN DU PEDALEUR ET REPENTIGNY QC',
                                      'AVANT-GARDE MONTREAL QC',
                                      'CREMERIE LEGARDEUR REPENTIGNY QC',
                                      'DELICES LACTES POINTE AUX TRQC',
                                      'ERABLIERE AU RYTHME DES TSAINT-LIN-LAUQC',
                                      'LAITERIE COATICOOK COATICOOK QC',
                                      "MCDONALD'S #10630 Q04 BERTHIERVILLEQC",
                                      'PETITE MARCHE MONTREAL QC',
                                      'ROCKY MOUNTAIN CHOCOLATE MONT-TREMBLANQC',
                                      'TIM HORTONS #1151 MONTREAL QC'
                                      'TOMATE BASILIC PAT POINTE-AUX-TRQC',
                                      'A&W',
                                      "MCDONALD",
                                      'Tim Hortons',
                                      "Mcdonald's",
                                      "L' Echoppe Des Fromage",
                                      'Restaurant Le Boucan',
                                      'Spanel Crepes Et Gourm',
                                      'Kumamoto Ramen',
                                      'Grumpys Bar',
                                      'Lsp*Canton Brasse',

                                      ],
    'Electricity': ['HYDRO-QUEBEC']
}
