# Generated by Django 4.2 on 2026-04-07 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_customuser_family_familymember'),
        ('accounting', '0003_seed_statcan_master'),
        ('planning', '0002_annuityratehistory'),
        ('banking', '0018_file_field_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TangibleAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('purchase_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_market_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(help_text="The dedicated ledger account representing this asset's book value.", on_delete=django.db.models.deletion.CASCADE, related_name='tangible_asset', to='accounting.account')),
                ('annuity_schedule', models.ForeignKey(blank=True, help_text='Associated financing schedule (e.g. Mortgage).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tangible_assets', to='planning.annuityschedule')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tangible_assets', to='users.family')),
                ('member', models.ForeignKey(blank=True, help_text='Primary owner within the family (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tangible_assets', to='users.familymember')),
                ('staged_transaction', models.ForeignKey(blank=True, help_text='Link to the original purchase transaction if imported via statement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tangible_assets', to='banking.stagedtransaction')),
            ],
        ),
    ]
