# Generated by Django on programmatic edit
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=512)),
                ('num_floors', models.IntegerField(blank=True, null=True)),
                ('tangible_asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='house_asset', to='assets.tangibleasset')),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='assets.houseasset')),
            ],
            options={
                'ordering': ['floor_number'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('length', models.DecimalField(decimal_places=2, max_digits=8, help_text='Meters')),
                ('width', models.DecimalField(decimal_places=2, max_digits=8, help_text='Meters')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, help_text='Meters')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='assets.floor')),
            ],
        ),
        migrations.CreateModel(
            name='Window',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(decimal_places=2, max_digits=6, help_text='Meters')),
                ('width', models.DecimalField(decimal_places=2, max_digits=6, help_text='Meters')),
                ('quantity', models.IntegerField(default=1)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='assets.room')),
            ],
        ),
    ]
