# Generated by Django 4.2 on 2026-05-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_house_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='tangibleasset',
            name='contract_document',
            field=models.FileField(blank=True, help_text='Optional PDF or image of the purchase contract.', null=True, upload_to='contracts/assets/'),
        ),
    ]
