# Generated by Django 4.2 on 2026-05-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_tangibleasset_contract_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tangibleasset',
            name='contract_document',
        ),
        migrations.AddField(
            model_name='tangibleasset',
            name='sales_contract',
            field=models.FileField(blank=True, help_text='Optional PDF or image of the bill of sale / purchase contract.', null=True, upload_to='contracts/sales/'),
        ),
    ]
