# Generated by Django 6.0.3 on 2026-03-16 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('users', '0002_family_customuser_family_residence'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalMerchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(max_length=255)),
                ('default_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='global_merchants', to='accounting.account')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_regex', models.CharField(max_length=512)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='categorization.globalmerchant')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateMerchantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_post', models.BooleanField(default=False)),
                ('custom_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='private_merchant_configs', to='accounting.account')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_configs', to='users.family')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_configs', to='categorization.globalmerchant')),
            ],
            options={
                'unique_together': {('family', 'merchant')},
            },
        ),
    ]
