# Generated by Django 6.0.3 on 2026-03-18 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0003_seed_statcan_master'),
        ('banking', '0006_stagedtransaction_clean_description_and_more'),
        ('users', '0002_alter_customuser_family_familymember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('default_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchants', to='accounting.account')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchants', to='users.family')),
            ],
            options={
                'unique_together': {('family', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TransactionMappingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_text', models.CharField(max_length=255)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapping_rules', to='banking.financialinstitution')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_rules', to='categorization.merchant')),
            ],
        ),
    ]
