# Generated by Django 6.0.3 on 2026-03-17 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorization', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemerchantconfig',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_configs', to='users.family'),
        ),
        migrations.AddField(
            model_name='privatemerchantconfig',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_configs', to='categorization.globalmerchant'),
        ),
        migrations.AlterUniqueTogether(
            name='privatemerchantconfig',
            unique_together={('family', 'merchant')},
        ),
    ]
