# Generated by Django 6.0.3 on 2026-03-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='is_unique_provider',
            field=models.BooleanField(default=True),
        ),
    ]
