# Generated by Django 6.0.3 on 2026-03-16 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_seed_default_accounts'),
        ('categorization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalmerchant',
            name='default_account',
        ),
        migrations.AddField(
            model_name='globalmerchant',
            name='default_statcan_account',
            field=models.ForeignKey(blank=True, help_text='Points to the global StatCan template account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='global_merchants', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='globalmerchant',
            name='canonical_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
