# Generated by Django 6.0.3 on 2026-03-17 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_seed_statcan_master'),
        ('banking', '0005_bankstatementimport_document_date_and_more'),
        ('categorization', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionMappingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_text', models.CharField(max_length=255)),
                ('merchant_name', models.CharField(max_length=255)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_mapping_rules', to='banking.financialinstitution')),
                ('target_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_mapping_rules', to='accounting.account')),
            ],
            options={
                'unique_together': {('search_text', 'institution')},
            },
        ),
    ]
