# Generated by Django 6.0.3 on 2026-03-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorization', '0002_merchant_is_unique_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmappingrule',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transactionmappingrule',
            name='min_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
