# Generated by Django 4.2 on 2026-03-23 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_seed_statcan_master'),
        ('categorization', '0003_transactionmappingrule_max_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmappingrule',
            name='override_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapping_rules_overrides', to='accounting.account'),
        ),
    ]
