# Generated by Django 4.2 on 2026-03-26 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorization', '0004_transactionmappingrule_override_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionmappingrule',
            name='override_account',
        ),
    ]
