# Generated by Django 4.2 on 2026-04-07 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_annuityratehistory'),
        ('categorization', '0005_remove_transactionmappingrule_override_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmappingrule',
            name='linked_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapping_rules', to='planning.annuityschedule'),
        ),
    ]
