# Generated by Django 4.2 on 2026-05-20 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_annuityratehistory'),
        ('categorization', '0006_transactionmappingrule_linked_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='linked_schedule',
            field=models.ForeignKey(blank=True, help_text='When set, approved payments for this merchant are split into principal + interest instead of a single expense line.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_merchants', to='planning.annuityschedule'),
        ),
    ]
