# Generated by Django 4.2 on 2026-03-26 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0003_seed_statcan_master'),
        ('users', '0002_alter_customuser_family_familymember'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnuitySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('schedule_type', models.CharField(choices=[('LOAN_AMORTIZATION', 'Loan / Mortgage'), ('SINKING_FUND', 'Sinking Fund')], max_length=30)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('annual_rate', models.DecimalField(decimal_places=4, max_digits=7)),
                ('n_periods', models.IntegerField()),
                ('payment_frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('BIWEEKLY', 'Bi-weekly'), ('WEEKLY', 'Weekly'), ('ANNUALLY', 'Annually')], max_length=20)),
                ('start_date', models.DateField()),
                ('computed_payment', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annuity_schedules', to='users.family')),
                ('linked_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annuity_schedule', to='accounting.journalentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnuityPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.IntegerField()),
                ('payment_date', models.DateField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interest_portion', models.DecimalField(decimal_places=2, max_digits=14)),
                ('principal_portion', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('is_paid', models.BooleanField(default=False)),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annuity_period', to='accounting.journalentry')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='planning.annuityschedule')),
            ],
            options={
                'ordering': ['period_number'],
                'unique_together': {('schedule', 'period_number')},
            },
        ),
    ]
