# Generated by Django 4.2 on 2026-04-07 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnuityRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('annual_rate', models.DecimalField(decimal_places=4, max_digits=7)),
                ('annuity_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_history', to='planning.annuityschedule')),
            ],
            options={
                'ordering': ['-effective_date'],
                'unique_together': {('annuity_schedule', 'effective_date')},
            },
        ),
    ]
