# Generated by Django 4.2 on 2026-05-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_annuityratehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='annuityschedule',
            name='contract_document',
            field=models.FileField(blank=True, help_text='Optional PDF or image of the loan agreement.', null=True, upload_to='contracts/loans/'),
        ),
    ]
