# Generated by Django 4.2 on 2026-05-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_annuityschedule_contract_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annuityschedule',
            name='contract_document',
        ),
        migrations.AddField(
            model_name='annuityschedule',
            name='financing_contract',
            field=models.FileField(blank=True, help_text='Optional PDF or image of the loan / mortgage agreement.', null=True, upload_to='contracts/financing/'),
        ),
    ]
