# Generated by Django 6.0.3 on 2026-03-17 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatementImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='statements/')),
                ('status', models.CharField(default='PROCESSING', max_length=50)),
                ('raw_ai_extraction', models.JSONField(blank=True, null=True)),
                ('validation_errors', models.JSONField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StagedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_date', models.DateField()),
                ('raw_description', models.CharField(max_length=1024)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unique_bank_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('UNPROCESSED', 'Unprocessed'), ('PENDING_REVIEW', 'Pending Review'), ('RECONCILED', 'Reconciled')], default='UNPROCESSED', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('CHECKING', 'Checking'), ('SAVINGS', 'Savings'), ('CREDIT_CARD', 'Credit Card'), ('LOAN', 'Loan'), ('INVESTMENT', 'Investment')], max_length=50)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='financial_product', to='accounting.account')),
            ],
        ),
    ]
