# Generated by Django 6.0.3 on 2026-03-16 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('users', '0002_family_customuser_family_residence'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('CHECKING', 'Checking'), ('SAVINGS', 'Savings'), ('CREDIT_CARD', 'Credit Card'), ('LOAN', 'Loan'), ('INVESTMENT', 'Investment')], max_length=50)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='financial_product', to='accounting.account')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_products', to='users.family')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='banking.financialinstitution')),
            ],
        ),
        migrations.CreateModel(
            name='StagedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_date', models.DateField()),
                ('raw_description', models.CharField(max_length=1024)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unique_bank_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('UNPROCESSED', 'Unprocessed'), ('PENDING_REVIEW', 'Pending Review'), ('RECONCILED', 'Reconciled')], default='UNPROCESSED', max_length=50)),
                ('financial_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staged_transactions', to='banking.financialproduct')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staged_transactions', to='accounting.journalentry')),
            ],
        ),
    ]
