# Generated by Django 6.0.3 on 2026-03-17 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('banking', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialproduct',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_products', to='users.family'),
        ),
        migrations.AddField(
            model_name='financialproduct',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='banking.financialinstitution'),
        ),
        migrations.AddField(
            model_name='bankstatementimport',
            name='financial_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_imports', to='banking.financialproduct'),
        ),
        migrations.AddField(
            model_name='stagedtransaction',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staged_transactions', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='stagedtransaction',
            name='statement_import',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staged_transactions', to='banking.bankstatementimport'),
        ),
    ]
