# Generated by Django 6.0.3 on 2026-03-16 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_seed_financial_institutions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagedtransaction',
            name='financial_product',
        ),
        migrations.AddField(
            model_name='stagedtransaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='BankStatementImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='statements/')),
                ('status', models.CharField(default='PROCESSING', max_length=50)),
                ('raw_ai_extraction', models.JSONField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('financial_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_imports', to='banking.financialproduct')),
            ],
        ),
        migrations.AddField(
            model_name='stagedtransaction',
            name='statement_import',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staged_transactions', to='banking.bankstatementimport'),
        ),
    ]
