# Generated by Django 6.0.3 on 2026-03-17 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_seed_financial_institutions'),
        ('users', '0002_alter_customuser_family_familymember'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialproduct',
            name='account_number',
            field=models.CharField(blank=True, help_text='The exact account, contract, or card number used for statement reconciliation.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='financialproduct',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_products', to='users.familymember'),
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='product_type',
            field=models.CharField(choices=[('CHECKING', 'Checking'), ('SAVINGS', 'Savings'), ('CREDIT_CARD', 'Credit Card'), ('LOAN', 'Loan'), ('INVESTMENT', 'Investment'), ('REGISTERED', 'Registered Account')], max_length=50),
        ),
    ]
