# Generated by Django 6.0.3 on 2026-03-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_remove_stagedtransaction_financial_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementimport',
            name='validation_errors',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
