# Generated by Django 6.0.3 on 2026-03-17 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_seed_statcan_master'),
        ('banking', '0004_financialproduct_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementimport',
            name='document_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankstatementimport',
            name='processed_by_ai',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bankstatementimport',
            name='processed_by_python',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bankstatementimport',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='statements/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='bankstatementimport',
            name='status',
            field=models.CharField(choices=[('STAGED', 'Staged'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('VALIDATION_FAILED', 'Validation Failed')], default='STAGED', max_length=50),
        ),
        migrations.AlterField(
            model_name='stagedtransaction',
            name='statement_import',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staged_transactions', to='banking.bankstatementimport'),
        ),
        migrations.AlterField(
            model_name='stagedtransaction',
            name='unique_bank_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='stagedtransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('unique_bank_id__isnull', False)), fields=('statement_import', 'unique_bank_id'), name='unique_transaction_per_import'),
        ),
    ]
