# Generated by Django 6.0.3 on 2026-03-18 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_seed_statcan_master'),
        ('banking', '0005_bankstatementimport_document_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagedtransaction',
            name='clean_description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='stagedtransaction',
            name='predicted_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicted_for_transactions', to='accounting.account'),
        ),
    ]
