# Generated by Django 6.0.3 on 2026-03-20 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0006_stagedtransaction_clean_description_and_more'),
        ('categorization', '0002_merchant_is_unique_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagedtransaction',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staged_transactions', to='categorization.merchant'),
        ),
    ]
