# Generated by Django 6.0.3 on 2026-03-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_seed_statcan_master'),
        ('banking', '0008_backfill_stagedtransaction_merchant'),
        ('categorization', '0002_merchant_is_unique_provider'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stagedtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('clean_description__isnull', True), ('merchant__isnull', False), _connector='OR'), name='clean_description_requires_merchant', violation_error_message='If clean_description is set, merchant_id must not be NULL. Enforcing strict FK linkage.'),
        ),
    ]
