# Generated by Django 6.0.3 on 2026-03-20 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0009_stagedtransaction_clean_description_requires_merchant'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stagedtransaction',
            name='clean_description_requires_merchant',
        ),
        migrations.RemoveField(
            model_name='stagedtransaction',
            name='clean_description',
        ),
    ]
