# Generated by Django 6.0.3 on 2026-03-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0010_remove_stagedtransaction_clean_description_requires_merchant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagedtransaction',
            name='clean_description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
