# Generated by Django 4.2 on 2026-03-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0011_stagedtransaction_clean_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementimport',
            name='shadow_mode_mismatch',
            field=models.BooleanField(default=False),
        ),
    ]
