# Generated by Django 4.2 on 2026-03-22 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0012_bankstatementimport_shadow_mode_mismatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagedtransaction',
            name='clean_description',
        ),
    ]
