# Generated by Django 4.2 on 2026-03-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0013_remove_stagedtransaction_clean_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementimport',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
