# Generated by Django 4.2 on 2026-03-25 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_seed_statcan_master'),
        ('banking', '0014_bankstatementimport_file_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagedtransaction',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staged_transactions', to='accounting.journalentry'),
        ),
    ]
