# Generated by Django 4.2 on 2026-03-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0015_alter_stagedtransaction_journal_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementimport',
            name='processing_log',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
