# Generated by Django 4.2 on 2026-03-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0017_institutional_ingestion_phase1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatementimport',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='statements/%Y/%m/'),
        ),
    ]
