# Generated by Django 4.2 on 2026-04-13 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0018_file_field_max_length'),
        ('users', '0002_alter_customuser_family_familymember'),
        ('accounting', '0003_seed_statcan_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsistencyReportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_source', models.CharField(choices=[('MANUAL', 'Manual'), ('CLI', 'Command Line'), ('LEDGER_RESET', 'Ledger Reset'), ('REPROCESS', 'Reprocess')], max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('scope', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consistency_report_runs', to='users.family')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ConsistencyReportFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], max_length=16)),
                ('category', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consistency_findings', to='accounting.journalentry')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='quality.consistencyreportrun')),
                ('staged_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consistency_findings', to='banking.stagedtransaction')),
                ('statement_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consistency_findings', to='banking.bankstatementimport')),
                ('transaction_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consistency_findings', to='accounting.transactionline')),
            ],
            options={
                'ordering': ['severity', 'category', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='consistencyreportrun',
            index=models.Index(fields=['family', 'status', '-started_at'], name='quality_con_family__854fb6_idx'),
        ),
        migrations.AddIndex(
            model_name='consistencyreportrun',
            index=models.Index(fields=['family', 'trigger_source', '-started_at'], name='quality_con_family__3c740e_idx'),
        ),
        migrations.AddIndex(
            model_name='consistencyreportfinding',
            index=models.Index(fields=['run', 'severity'], name='quality_con_run_id_e41559_idx'),
        ),
        migrations.AddIndex(
            model_name='consistencyreportfinding',
            index=models.Index(fields=['run', 'category'], name='quality_con_run_id_e52340_idx'),
        ),
    ]
