# Generated by Django 6.0.3 on 2026-03-17 00:41

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='family',
            field=models.ForeignKey(blank=True, help_text='If null, this is a system-wide standard account.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='users.family'),
        ),
        migrations.AddField(
            model_name='account',
            name='global_reference',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Link to the global StatCan master template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloned_accounts', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='account',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='users.family'),
        ),
        migrations.AddField(
            model_name='transactionline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_lines', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='transactionline',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry'),
        ),
    ]
