# Generated by Django 6.0.3 on 2026-03-16 20:27

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_seed_default_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='global_reference',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Link to the global StatCan master template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloned_accounts', to='accounting.account'),
        ),
    ]
