# Generated by Django 4.2 on 2026-04-15 12:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_analysisrun_and_insightfact_run_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMonthlyStat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_id', models.IntegerField(db_index=True, help_text='Foreign key to Account (category)')),
                ('month', models.DateField(db_index=True, help_text="First day of the month (DATE_TRUNC('month', date))")),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all transaction amounts for the category in the month', max_digits=15)),
                ('transaction_count', models.IntegerField(default=0, help_text='Count of transactions for the category in the month')),
                ('avg_ticket', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average transaction amount (total_amount / transaction_count)', max_digits=15)),
            ],
            options={
                'verbose_name': 'Category Monthly Stat',
                'verbose_name_plural': 'Category Monthly Stats',
                'db_table': 'accounting_categorymonthlystat',
                'managed': False,
            },
        ),
        migrations.RenameIndex(
            model_name='analysisrun',
            new_name='accounting__family__e670ed_idx',
            old_name='accounting_a_family__idx',
        ),
        migrations.RenameIndex(
            model_name='analysisrun',
            new_name='accounting__status_c9a465_idx',
            old_name='accounting_a_status__idx',
        ),
        migrations.RenameIndex(
            model_name='insightfact',
            new_name='accounting__categor_6be19c_idx',
            old_name='accounting_i_categor_idx',
        ),
        migrations.RenameIndex(
            model_name='insightfact',
            new_name='accounting__compute_4277db_idx',
            old_name='accounting_i_compute_idx',
        ),
        migrations.AddField(
            model_name='insightfact',
            name='projected_lower_bound',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lower bound of the 95% prediction interval (Confidence Corridor)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='insightfact',
            name='projected_upper_bound',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Upper bound of the 95% prediction interval (Confidence Corridor)', max_digits=12, null=True),
        ),
    ]
