# Generated by Django 4.2 on 2026-05-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_add_external_normalization_to_insightfact'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='statcan_vector_id',
            field=models.IntegerField(blank=True, help_text='StatCan WDS vector ID for the CPI series that approximates inflation for this account category.', null=True),
        ),
    ]
