# Generated by Django 4.2 on 2026-05-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_add_statcan_vector_id_to_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='status',
            field=models.CharField(choices=[('PRIMARY', 'Primary'), ('ADJUSTMENT', 'Adjustment'), ('VOID', 'Void')], default='PRIMARY', help_text='Status of the entry: PRIMARY (actual spend), ADJUSTMENT (ledger correction), or VOID (cancelled).', max_length=20),
        ),
    ]
